/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author Gemo
 */
public class Informes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Informes
     */
    public Informes() {
        initComponents();
        
        this.setIconifiable(true);   
        this.setResizable(true);  
        this.setClosable(true);   
        this.setMaximizable(true);
       
       // lRight1.setVisible(false);
       
        lRight4.setVisible(false);
        
     
        
        //lRight9.setVisible(false);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        tfFechaInicio3 = new javax.swing.JTextField();
        pSesionesFecha = new javax.swing.JTabbedPane();
        pItinerariosFecha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btVolver1 = new javax.swing.JButton();
        btCrear2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dateTextField1 = new calendario.DateTextField();
        dateTextField2 = new calendario.DateTextField();
        jPanel2 = new javax.swing.JPanel();
        btVolver2 = new javax.swing.JButton();
        btCrear1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateTextField3 = new calendario.DateTextField();
        dateTextField4 = new calendario.DateTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox();
        btVolver3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfAnno = new javax.swing.JTextField();
        lRight4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btVolver5 = new javax.swing.JButton();
        btCrear5 = new javax.swing.JButton();
        dateTextField8 = new calendario.DateTextField();
        jLabel11 = new javax.swing.JLabel();
        dateTextField7 = new calendario.DateTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btVolver4 = new javax.swing.JButton();
        btCrear3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateTextField5 = new calendario.DateTextField();
        dateTextField6 = new calendario.DateTextField();

        tfFechaInicio3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFechaInicio2KeyTyped(evt);
            }
        });

        setTitle("Crear informes");

        jLabel3.setText("Fecha inicio:");

        btVolver1.setText("Volver");
        btVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolver1ActionPerformed(evt);
            }
        });

        btCrear2.setText("Crear informe");
        btCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrear2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha fin:");

        dateTextField1.setText("dateTextField1");

        dateTextField2.setText("dateTextField2");

        javax.swing.GroupLayout pItinerariosFechaLayout = new javax.swing.GroupLayout(pItinerariosFecha);
        pItinerariosFecha.setLayout(pItinerariosFechaLayout);
        pItinerariosFechaLayout.setHorizontalGroup(
            pItinerariosFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pItinerariosFechaLayout.createSequentialGroup()
                .addGroup(pItinerariosFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pItinerariosFechaLayout.createSequentialGroup()
                        .addContainerGap(199, Short.MAX_VALUE)
                        .addComponent(btCrear2)
                        .addGap(18, 18, 18)
                        .addComponent(btVolver1))
                    .addGroup(pItinerariosFechaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pItinerariosFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(dateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pItinerariosFechaLayout.setVerticalGroup(
            pItinerariosFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pItinerariosFechaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(pItinerariosFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVolver1)
                    .addComponent(btCrear2))
                .addContainerGap())
        );

        pSesionesFecha.addTab("Itinerarios: fecha", pItinerariosFecha);

        btVolver2.setText("Volver");
        btVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolver2ActionPerformed(evt);
            }
        });

        btCrear1.setText("Crear informe");
        btCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrear1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha inicio:");

        jLabel4.setText("Fecha fin:");

        dateTextField3.setText("dateTextField3");

        dateTextField4.setText("dateTextField4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(199, Short.MAX_VALUE)
                        .addComponent(btCrear1)
                        .addGap(18, 18, 18)
                        .addComponent(btVolver2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(dateTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVolver2)
                    .addComponent(btCrear1))
                .addContainerGap())
        );

        pSesionesFecha.addTab("Sesiones: fecha", jPanel2);

        jLabel5.setText("Elige el mes y el año:");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        btVolver3.setText("Volver");
        btVolver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolver3ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Informe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("/");

        tfAnno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAnnoKeyTyped(evt);
            }
        });

        lRight4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/right.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lRight4)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btVolver3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRight4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVolver3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pSesionesFecha.addTab("Entrenamiento semanal", jPanel3);

        btVolver5.setText("Volver");
        btVolver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolver5ActionPerformed(evt);
            }
        });

        btCrear5.setText("Crear Informe");
        btCrear5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrear5ActionPerformed(evt);
            }
        });

        dateTextField8.setText("dateTextField6");

        jLabel11.setText("Fecha fin:");

        dateTextField7.setText("dateTextField5");

        jLabel12.setText("Fecha inicio:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(btCrear5)
                .addGap(18, 18, 18)
                .addComponent(btVolver5)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel12)
                .addGap(11, 11, 11)
                .addComponent(dateTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVolver5)
                    .addComponent(btCrear5))
                .addContainerGap())
        );

        pSesionesFecha.addTab("Itinerarios: dificultad", jPanel5);

        btVolver4.setText("Volver");
        btVolver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolver4ActionPerformed(evt);
            }
        });

        btCrear3.setText("Crear informe");
        btCrear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrear3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha inicio:");

        jLabel10.setText("Fecha fin:");

        dateTextField5.setText("dateTextField5");

        dateTextField6.setText("dateTextField6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCrear3)
                .addGap(18, 18, 18)
                .addComponent(btVolver4)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addComponent(dateTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVolver4)
                    .addComponent(btCrear3))
                .addContainerGap())
        );

        pSesionesFecha.addTab("Sesiones: tipo", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pSesionesFecha)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pSesionesFecha, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVolver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolver3ActionPerformed
        this.hide();
    }//GEN-LAST:event_btVolver3ActionPerformed

    private void btVolver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolver4ActionPerformed
        this.hide();
    }//GEN-LAST:event_btVolver4ActionPerformed

    private void btCrear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrear3ActionPerformed
       // if (lRight1.isVisible()){
            
            //Introducir aquí el código para generar informes
             Connection connection = null;
        try
        {
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:./db/escalador.db", "sa","");
             Map parametros = new HashMap();
            Timestamp ini= new Timestamp(dateTextField5.getDate().getTime());
            Timestamp fin= new Timestamp(dateTextField6.getDate().getTime());
            parametros.put("fechainicio", ini);
            parametros.put("fechafin", fin);
            JasperPrint print = JasperFillManager.fillReport("./informes/consulta4.jasper", parametros,connection);
            JasperExportManager.exportReportToPdfFile(print,"./informesgenerados/sesionestipo.pdf");
             
        }
        catch (Throwable e)
        {
            e.printStackTrace();
        }
        finally
        {
      
            try {if (connection !=null) connection.close();} catch(Throwable e){};
        }
            
            this.hide();
            
//        } else {
//            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
//        }
    }//GEN-LAST:event_btCrear3ActionPerformed

    private void tfAnnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAnnoKeyTyped
         if (!"".equals(tfAnno.getText())){
            lRight4.setVisible(true);
        } else {
            lRight4.setVisible(false);
        }
    }//GEN-LAST:event_tfAnnoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //// entrenamientosemanal
        if (lRight4.isVisible()){
            
            //Introducir aquí el código para generar informes
              Connection connection = null;
        try
        {
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:./db/escalador.db", "sa","");
            Map parametros = new HashMap();
            parametros.put("anio", Integer.valueOf(tfAnno.getText()));
            parametros.put("mes",Integer.valueOf(cbMes.getSelectedIndex())+1);
            JasperPrint print = JasperFillManager.fillReport("./informes/consulta3.jasper", parametros,connection);
            JasperExportManager.exportReportToPdfFile(print,"./informesgenerados/entrenamientosemanal.pdf");
             
        }
        catch (Throwable e)
        {
            e.printStackTrace();
        }
        finally
        {
      
            try {if (connection !=null) connection.close();} catch(Throwable e){};
        }
            
            this.hide();
            
        } else {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrear2ActionPerformed
     // itinerarios
            //Introducir aquí el código para generar informes
        Connection connection = null;
        try
        {
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:./db/escalador.db", "sa","");
             Map parametros = new HashMap();
            Timestamp ini= new Timestamp(dateTextField1.getDate().getTime());
            Timestamp fin= new Timestamp(dateTextField2.getDate().getTime());
            parametros.put("fechainicio", ini);
            parametros.put("fechafin", fin);
            JasperPrint print = JasperFillManager.fillReport("./informes/consulta1.jasper", parametros,connection);
            JasperExportManager.exportReportToPdfFile(print,"./informesgenerados/itinerarios.pdf");
             
        }
        catch (Throwable e)
        {
            e.printStackTrace();
        }
        finally
        {
      
            try {if (connection !=null) connection.close();} catch(Throwable e){};
        }
      
            
            this.hide();
    }//GEN-LAST:event_btCrear2ActionPerformed

    private void btVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolver1ActionPerformed
        this.hide();
    }//GEN-LAST:event_btVolver1ActionPerformed

    private void btVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolver2ActionPerformed
        this.hide();
    }//GEN-LAST:event_btVolver2ActionPerformed

    private void btCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrear1ActionPerformed
            //sesiones
            //Introducir aquí el código para generar informes
         Connection connection = null;
        try
        {
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:./db/escalador.db", "sa","");
             Map parametros = new HashMap();
            Timestamp ini= new Timestamp(dateTextField3.getDate().getTime());
            Timestamp fin= new Timestamp(dateTextField4.getDate().getTime());
            parametros.put("fechainicio", ini);
            parametros.put("fechafin",fin);
            JasperPrint print = JasperFillManager.fillReport("./informes/consulta2.jasper", parametros,connection);
            JasperExportManager.exportReportToPdfFile(print,"./informesgenerados/sesiones.pdf");
             
        }
        catch (Throwable e)
        {
            e.printStackTrace();
        }
        finally
        {
      
            try {if (connection !=null) connection.close();} catch(Throwable e){};
        }
            
            this.hide();
    }//GEN-LAST:event_btCrear1ActionPerformed

    private void btVolver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolver5ActionPerformed
        this.hide();
    }//GEN-LAST:event_btVolver5ActionPerformed

    private void btCrear5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrear5ActionPerformed
        //if (lRight9.isVisible()){
            
            //Introducir aquí el código para generar informes
             Connection connection = null;
            //cambiar esta ventana para introducir fechas
        try
        {
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:./db/escalador.db", "sa","");
             Map parametros = new HashMap();
             //cambiar al nuevo campo fechas
            Timestamp ini= new Timestamp(dateTextField7.getDate().getTime());
            Timestamp fin= new Timestamp(dateTextField8.getDate().getTime());
            parametros.put("fechainicio", ini);
            parametros.put("fechafin", fin);
            JasperPrint print = JasperFillManager.fillReport("./informes/consulta5.jasper", parametros,connection);
            JasperExportManager.exportReportToPdfFile(print,"./informesgenerados/itinerariosdificultad.pdf");
             
        }
        catch (Throwable e)
        {
            e.printStackTrace();
        }
        finally
        {
      
            try {if (connection !=null) connection.close();} catch(Throwable e){};
        }
            
            this.hide();
            
            this.hide();
            
//        } else {
//            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
//        }
    }//GEN-LAST:event_btCrear5ActionPerformed

    private void tfFechaInicio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFechaInicio2KeyTyped
       
    }//GEN-LAST:event_tfFechaInicio2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrear1;
    private javax.swing.JButton btCrear2;
    private javax.swing.JButton btCrear3;
    private javax.swing.JButton btCrear5;
    private javax.swing.JButton btVolver1;
    private javax.swing.JButton btVolver2;
    private javax.swing.JButton btVolver3;
    private javax.swing.JButton btVolver4;
    private javax.swing.JButton btVolver5;
    private javax.swing.JComboBox cbMes;
    private calendario.DateTextField dateTextField1;
    private calendario.DateTextField dateTextField2;
    private calendario.DateTextField dateTextField3;
    private calendario.DateTextField dateTextField4;
    private calendario.DateTextField dateTextField5;
    private calendario.DateTextField dateTextField6;
    private calendario.DateTextField dateTextField7;
    private calendario.DateTextField dateTextField8;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lRight4;
    private javax.swing.JPanel pItinerariosFecha;
    private javax.swing.JTabbedPane pSesionesFecha;
    private javax.swing.JTextField tfAnno;
    private javax.swing.JTextField tfFechaInicio3;
    // End of variables declaration//GEN-END:variables
}
