/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import calendario.CambioFechaListener;
import enlace_datos_gui.BridgeSesion;
import javax.swing.JTabbedPane;

public class ListadoSesiones extends javax.swing.JInternalFrame {

    private BridgeSesion bridge = BridgeSesion.BRIDGE;

    /**
     * Creates new form Itinerarios
     */
    public ListadoSesiones() {

        initComponents();
        this.setIconifiable(true);
        this.setResizable(true);
        this.setClosable(true);
        this.setMaximizable(true);
        //Añado la tabla al bridge para que al insertar o modificar sesions se actualice la tabla
        bridge.addTablaSesiones(tbListado);
        bridge.loadAllSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListado = new gui.tablasesion.TablaSesiones();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlVacio = new javax.swing.JPanel();
        pnlRangoFechas = new gui.PanelRangoFechas();
        pnlTipoSesion = new gui.PanelTipoSesion();

        setResizable(true);
        setTitle("Listado sesiones");
        setMinimumSize(new java.awt.Dimension(575, 380));
        setPreferredSize(new java.awt.Dimension(575, 380));

        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        tbListado.setRowHeight(25);
        jScrollPane2.setViewportView(tbListado);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlVacioLayout = new javax.swing.GroupLayout(pnlVacio);
        pnlVacio.setLayout(pnlVacioLayout);
        pnlVacioLayout.setHorizontalGroup(
            pnlVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        pnlVacioLayout.setVerticalGroup(
            pnlVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar todas", pnlVacio);

        pnlRangoFechas.addCambioFechaListener(new CambioFechaListener(){
            @Override
            public void onCambioFecha() {
                bridge.loadByRange(pnlRangoFechas.getFecha1(), pnlRangoFechas.getFecha2());
            }
        });
        jTabbedPane1.addTab("Listar por fecha", pnlRangoFechas);
        jTabbedPane1.addTab("Listar por tipo", pnlTipoSesion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btVolver)
                    .addComponent(jScrollPane2))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVolver)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción ejecutada al pulsar en volver
     * @param evt 
     */
    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btVolverActionPerformed
    /**
     * Al cambiar de pestaña se aplica el filtro adecuado a los datos de la
     * tabla
     * @param evt 
     */
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        JTabbedPane tab = (JTabbedPane) evt.getSource();
        bridge.setCurrentTab(tab.getSelectedIndex());
        switch (tab.getSelectedIndex()) {
            case 0:
                bridge.loadAllSesion();
                break;
            case 1:
                bridge.loadByRange(pnlRangoFechas.getFecha1(), pnlRangoFechas.getFecha2());
                break;
            case 2:
                bridge.loadByTipo(pnlTipoSesion.getTipoSesion());
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

   /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVolver;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.PanelRangoFechas pnlRangoFechas;
    private gui.PanelTipoSesion pnlTipoSesion;
    private javax.swing.JPanel pnlVacio;
    private gui.tablasesion.TablaSesiones tbListado;
    // End of variables declaration//GEN-END:variables
}
