/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author Canela
 */
public class PnlAltaModifItinerarios extends javax.swing.JPanel {

    /**
     * Creates new form PnlAltaModifItinerarios
     */
    public PnlAltaModifItinerarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreItinerario = new javax.swing.JLabel();
        labelLocalizacion = new javax.swing.JLabel();
        labelTipoItinerario = new javax.swing.JLabel();
        labelDificultad = new javax.swing.JLabel();
        btVolver = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        labelFechaResolucion = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        tfNombreItinerario = new javax.swing.JTextField();
        tfLocalizacionItinerario = new javax.swing.JTextField();
        cbTipoItineracio = new javax.swing.JComboBox();
        spDificultadNumero = new javax.swing.JSpinner();
        spDificultadLetra = new javax.swing.JSpinner();
        spDificultadMasMenos = new javax.swing.JSpinner();
        ftfFechaResolucion = new javax.swing.JFormattedTextField();
        tfUrlFoto = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(266, 264));

        labelNombreItinerario.setText("Nombre:");

        labelLocalizacion.setText("Localización:");

        labelTipoItinerario.setText("Tipo:");

        labelDificultad.setText("Dificultad:");

        btVolver.setText("Volver");

        btGuardar.setText("Guardar");

        labelFechaResolucion.setText("Fecha Resolución:");

        labelFoto.setText("Foto:");

        cbTipoItineracio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Via de escalada", "Boulder" }));

        spDificultadLetra.setModel(new javax.swing.SpinnerListModel(new String[] {"a", "b", "c"}));

        spDificultadMasMenos.setModel(new javax.swing.SpinnerListModel(new String[] {" ", "-", "+"}));

        ftfFechaResolucion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfFechaResolucion.setText("dd-MMM-aa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFoto)
                            .addComponent(labelFechaResolucion)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btVolver))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombreItinerario)
                            .addComponent(labelLocalizacion)
                            .addComponent(labelTipoItinerario)
                            .addComponent(labelDificultad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spDificultadNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(spDificultadLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spDificultadMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfLocalizacionItinerario)
                    .addComponent(cbTipoItineracio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUrlFoto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftfFechaResolucion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btGuardar))
                    .addComponent(tfNombreItinerario))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreItinerario)
                            .addComponent(tfNombreItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelLocalizacion))
                    .addComponent(tfLocalizacionItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoItinerario)
                    .addComponent(cbTipoItineracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDificultad)
                    .addComponent(spDificultadNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spDificultadLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spDificultadMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaResolucion)
                    .addComponent(ftfFechaResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFoto)
                    .addComponent(tfUrlFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVolver)
                    .addComponent(btGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btVolver;
    private javax.swing.JComboBox cbTipoItineracio;
    private javax.swing.JFormattedTextField ftfFechaResolucion;
    private javax.swing.JLabel labelDificultad;
    private javax.swing.JLabel labelFechaResolucion;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelLocalizacion;
    private javax.swing.JLabel labelNombreItinerario;
    private javax.swing.JLabel labelTipoItinerario;
    private javax.swing.JSpinner spDificultadLetra;
    private javax.swing.JSpinner spDificultadMasMenos;
    private javax.swing.JSpinner spDificultadNumero;
    private javax.swing.JTextField tfLocalizacionItinerario;
    private javax.swing.JTextField tfNombreItinerario;
    private javax.swing.JTextField tfUrlFoto;
    // End of variables declaration//GEN-END:variables
}
